------------------------------------------------------------------------------------------
-- Datas file
-- Written by Homeopatix
-- 17 avril 2021
------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------
-- DATA Tiers
------------------------------------------------------------------------------------------
---- Tier 1
	datasNormalFish = {0x410E1E56,
						0x410E1CD7,
						0x410E1CD7,
						0x410E1E52,
						0x410E1CD7,
						0x410E1E62,
						0x410E1E54,
						0x410E1E66,
						0x410E1E5C,
						0x410E1E5C,
						0x410E1E58,
						0x410E1E5A,
						0x410E1E5C,
						0x410E1E56,
						0x410E1E52,
						0x410E1E58,
						0x410E1E5A,
						0x410E1E64,
						0x410E1E62,
						0x410E1E68};
	datasRareFish = {0x410E3643,
						0x410E3647,
						0x410E363B,
						0x410E363F,
						0x410E3627,
						0x410E3635,
						0x410E3633,
						0x410E362D,
						0x410E3641,
						0x410E3631,
						0x410E3649,
						0x410E3639,
						0x410E3637,
						0x410E3629,
						0x410E363D,
						0x410E362B,
						0x410E362F,
						0x410E3645,
						0x410E1F75,
						0x410E1F71,
						0x410E1F75,
						0x410E1F67,
						0x410E1F73,
						0x410E1F6F,
						0x410E1F6B,
						0x410E1F69,
						0x410E1F6D};
	datasGarbageFish = {0x410E1F91,
						0x410E1F99,
						0x410E1F93,
						0x410E1F8F,
						0x410E1F9F,
						0x410E1F95,
						0x410E1F8D,
						0x410E1F9B,
						0x410E1F97,
						0x410E1F9D,
						0x410E2038};
	datasMountableWallFish = {0x410E3A47,
						0x410E3A49,
						0x410E3A49,
						0x410E3A4B,
						0x410E3A4B,
						0x410E3A4B,
						0x410E3A45,
						0x410E3A45,
						0x410E1519,
						0x410E1E62,
						0x410E1E62,
						0x410E1E5C,
						0x410E1CD7,
						0x410E1E5E,
						0x410E1E64,
						0x410E1E66,
						0x410E1CD7,
						0x410E1E5E,
						0x410E1E56,
						0x410E1E58,
						0x410E1E58,
						0x410E1E5E,
						0x410E1CD7,
						0x410E1E52,
						0x410E1E5C,
						0x410E1E62,
						0x410E1E5C,
						0x410E1E58,
						0x410E1E56};

	datasNormalLocation = {"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game",
							"All over the game"};
	datasRareLocation = {"Bree, Ered Luin, The Shire, Forochel, Angmar",
						"The Lone-lands, The North Downs, Forochel, Angmar",
						"Evendim, Forochel, The Trollshaws, Angmar",
						"Angmar, Forochel, The Misty Mountains",
						"The Lone-lands, The North Downs, Forochel, Angmar",
						"Evendim, The Trollshaws, Forochel, Angmar",
						"Angmar, Forochel, The Misty Mountains",
						"The Shire, The Lone-lands, Forochel, The North Downs",
						"The Lone-lands, The North Downs, Forochel, Angmar",
						"Bree-land, Ered Luin, The Shire, East Rohan, Enedwaith, Stone Hall",
						"Angmar, Forochel, The Misty Mountains, East Rohan, Enedwaith, Stone Hall",
						"Evendim, The Trollshaws, Havens of Belfalas, Enedwaith, Filikul instance (Moria), Stone Hall",
						"Evendim, The Trollshaws, Caras Galadhon, Enedwaith, Rohan",
						"Evendim, The Trollshaws, Enedwaith, Stone Hall",
						"The Lone-lands, The North Downs, Enedwaith, Stone Hall",
						"Bree-land, Ered Luin, The Shire, Stone Hall, Rohan, Enedwaith, Echad Sirion",
						"Angmar, Forochel, The Misty Mountains, Stone Hall, East Rohan, Enedwaith, Echad Sirion",
						"Evendim, The Trollshaws, Stone Hall, Enedwaith, Rohan",
						"Bree-land, Ered Luin, The Shire, Evendim",
						"The Lone-lands, The North Downs, Evendim",
						"The Trollshaws, Eryn Lasgalen and the Dale-lands, Evendim. ",
						"Angmar, Forochel, The Misty Mountains, Evendim",
						"Bree-land, Ered Luin, The Shire, Evendim",
						"The Lone-lands, The North Downs, Evendim, Eryn Lasgalen. ",
						"The Lone-lands, The North Downs, Lake Evendim in Evendim. ",
						"Angmar, Forochel, The Misty Mountains, Evendim",
						"Bree-land, Ered Luin, The Shire, Evendim"};
	datasGarbageFishLocation = {"All over the game",
								"All over the game",
								"All over the game",
								"All over the game",
								"All over the game",
								"All over the game",
								"All over the game",
								"All over the game",
								"All over the game",
								"All over the game",
								"All over the game"};
	datasMountableWallFishLocation = {"Bree-land, Ered Luin, The Shire, Evendim, Enedwaith",
										"The Lone-lands, The North Downs, Enedwaith",
										"Evendim, The Trollshaws, Enedwaith",
										"Angmar, Forochel, The Misty Mountains, Enedwaith",
										"Bree-land, Ered Luin, The Shire, Evendim, Enedwaith",
										"The Lone-lands, The North Downs, Enedwaith",
										"Evendim, The Trollshaws, Enedwaith",
										"Angmar, Forochel, The Misty Mountains, Enedwaith",
										"Angmar, Forochel, Evendim (Tinnudir), The Misty Mountains, Enedwaith, Dunland, Mirkwood, Great River",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game",
										"All over the game"};

	datasNormalFishNames = {"GoldFish",
							"Minnow",
							"Bitterling",
							"Charr",
							"Dace",
							"Barbel",
							"Smelt",
							"Catfish",
							"Rudd",
							"Bullhead",
							"Grayling",
							"Houting",
							"Perch",
							"Three-spined stickleback",
							"nine-spined stickleback",
							"Golden mullet",
							"Flounder",
							"Carp",
							"Pike",
							"Largemouth bass"};
	datasRareFishLVL = {"75",
						"85",
						"87",
						"90",
						"73",
						"80",
						"70",
						"100",
						"100",
						"60",
						"70",
						"75",
						"88",
						"75",
						"69",
						"80",
						"90",
						"100",
						"60",
						"50",
						"75",
						"90",
						"95",
						"80",
						"80",
						"70",
						"85"};
	datasRareFishNames = {"Bandfin darter",
							"Blackfin darter",
							"Bloodfin Darter",
							"FireBelly Darter",
							"Greenfin Darter",
							"Longfin Darter",
							"OrangeFin Darter",
							"Redfin Darter",
							"Splendidfin Darter",
							"Dwarf Sturgeon",
							"Fringebabel Sturgeon",
							"Green Sturgeon",
							"Lake Sturgeon",
							"Pallid Sturgeon",
							"Shortnose Sturgeon",
							"Shovelnose Sturgeon",
							"Starry Sturgeon",
							"White Sturgeon",
							"Brown Trout",
							"Bull Trout",
							"Cutthroat Trout",
							"Golden Trout",
							"Lake Trout",
							"Rainbow Trout",
							"Red-Spotted Trout",
							"Redband Trout",
							"Specled Trout"};
	datasGarbageFishNames = {"Rusty axe",
							"Dirty skull",
							"Rusty sword",
							"Drift-wood",
							"Rusty mace",
							"Old Boot",
							"Rusty hammer",
							"Ball of gunk",
							"Rusty dagger",
							"Weeds",
							"Spear head"};
	datasMountableWallFishLVL = {"10",
							"11",
							"30",
							"40",
							"50",
							"70",
							"80",
							"100",
							"186",
							"25",
							"155",
							"55",
							"10",
							"15",
							"135",
							"35",
							"20",
							"125",
							"1",
							"65",
							"115",
							"75",
							"6",
							"105",
							"85",
							"145",
							"50",
							"30",
							"95"};
	datasMountableWallFishNames = {"2-pound Salmon",
							"4-pound Salmon",
							"6-pound Salmon",
							"10-pound Salmon",
							"15-pound Salmon",
							"20-pound Salmon",
							"30-pound Salmon",
							"40-pound Salmon",
							"50-pound Salmon",
							"Barbarous Barbel",
							"Big Mouth Bass",
							"Brawny Bullhead",
							"Bright Bitterling",
							"Colourful Charr",
							"Courageous Carp",
							"Cunning Catfish",
							"Delightful Dace",
							"Fantastic Flounder",
							"Giant Goldfish",
							"Gleaming Grayling",
							"Great Golden Mullet",
							"Huge Houting",
							"Magnificent Minnow",
							"Nasty Nine-spined Stickleback",
							"Perfect Perch",
							"Perfect Pike",
							"Ruthless Rudd",
							"Superb Smelt",
							"Tricky Three-spined Stickleback"};

	DatasMasterNPC = {"Henry Oakeshott",
					"Refkell",
					"Brago Puddifoot",
					"Estmar Bolger",
					"Hald\195\186r",
					"Arnfin",
					"Arnfin",
					"Arnfin",
					"Arnfin",
					"Arnfin",
					"D\195\186drad",
					"D\195\186drad"};
	DatasMasterNPCExactPosition = {"Scholar's Stair Archives",
					"Hall of Kings",
					"Bywater Pool",
					"The Bird and Baby Inn",
					"The Hall of Fire",
					"The Twenty-first Hall",
					"Galtrev",
					"Snowbourn, Sutcrofts",
					"Forlaw",
					"Aldburg, Eastfold",
					"Edoras, Kingstead",
					"Dol Amroth, Havens of Belfalas"};
	DatasMasterNPCLocation = {"Bree-land",
					"Ered Luin",
					"The Shire",
					"The Shire",
					"Rivendell",
					"Moria",
					"Dunland",
					"East Rohan",
					"Wildermore",
					"West Rohan",
					"West Rohan",
					"Western Gondor"};
	DatasMasterNPCCoordExact = {"430", "380", -- bree
						"450", "310", -- ered luin
						"570", "420", -- the shire
						"260", "550", -- the shire
						"630", "380", -- fondcombe
						"675", "160", -- moria
						"430", "300", -- galtrev
						"730", "500", -- East rohan
						"460", "510", -- forloi
						"320", "440", -- west rohan
						"290", "590", -- west rohan
						"645", "450"}; -- western gondor
	DatasMasterNPCCoord = {"525", "535",
						"290", "70",
						"570", "420",
						"270", "560",
						"850", "220", -- fondcombe
						"490", "280",
						"450", "360",
						"400", "440",
						"640", "480",
						"320", "440",
						"470", "440",
						"470", "600"};

	DatasFishingRod = {"0x410DD1B3",
						"0x410DD1B3",
						"0x410DD1B3",
						"0x410DD1B3",
						"0x410DD1B3",
						"0x410DD1B3",
						"0x410DD1B3"};
	DatasFishingRodName = {"Basic Fishing Rod",
						"Yew Fishing Rod +1 Fishing",
						"Well-crafted Yew Fishing Rod +3 Fishing",
						"Lebethron Fishing Rod +4 Fishing",
						"Well-crafted Lebethron Fishing Rod +5 Fishing",
						"Rohirric Fishing Rod +8 Fishing",
						"Exquisite Elven Fishing Rod +10 Fishing"};
	DatasFishingRodLocation = {"Hobby Master",
							"Woodworker",
							"Woodworker",
							"Woodworker",
							"Woodworker",
							"Eastemnet Miscellany Quartermaster",
							"Quartermaster (Dwarves of Erebor Rewards) (Erebor)\n" ..
							"Quartermaster (Elves of Felegoth Rewards) (Felegoth)\n" ..
							"Quartermaster (Men of Dale Rewards) (Dale)"};

	DatasFishingQuests = {"[5] One Fish, Two Fish",
						"[5] Teach a Man to Fish",
						"[5] Fish-tales",
						"[40] Hook, Line, and Sinker",
						"[45] Fish of the wildwood",
						"[45] Fish of the wildwood",
						"[47] Empty Larder",
						"[75] Glinting in Forgotten Pools (repeatable)",
						"[85] Cuts of Fish",
						"[85] Terror of the Deep",
						"[85] The Blood-fish",
						"[85] The Garsfeld Guppy",
						"[87] The Last Cast",
						"[87] The Old River King!",
						"[99] Quest:Fishing on the Wharf (repeatable)",
						"[120] Cleaning the Anduin (repeatable)",
						"[120] Cleaning the Tributaries (repeatable)"};
	DatasFishingQuestsLocation = {"Estmar Bolger, The Bird and Baby Inn",
									"Henry Oakeshott, Scholar's Stair Archives",
									"Refkell, Hall of Kings",
									"Hald\195\186r, The Hall of Fire",
									"Hobby Master, Trader's Wharf",
									"Hobby Master, Trestlebridge Gate",
									"N\195\180ra, S\195\187ri-kyl\195\164",
									"Bron, Galtrev",
									"H\195\169alac, Snowbourn",
									"H\195\169alac, Snowbourn",
									"H\195\169alac, Snowbourn",
									"H\195\169alac, Snowbourn",
									"Th\195\169olac, Edoras",
									"Old River-king, Dock west of Edoras ",
									"An\195\173rwen, Docks of Dol Amroth",
									"Radagast, Radagast's Cottage",
									"Radagast, Radagast's Cottage"};

	DatasFishingQuestsLocationMap = {"The Shire",
									"Bree",
									"Ered Luin",
									"Rivendell Valley",
									"Wildwood",
									"Wildwood",
									"Forochel",
									"Dunland",
									"Sutcrofts",
									"Sutcrofts",
									"Sutcrofts",
									"Sutcrofts",
									"West Rohan",
									"West Rohan",
									"West Gondor",
									"Vales of Anduin",
									"Vales of Anduin"};
	DatasFishingQuestsCoord = {"270", "560",
						"525", "535",
						"290", "70",
						"850", "330",
						"450", "490",
						"850", "260",
						"540", "140",
						"450", "360",
						"400", "440",
						"400", "440",
						"400", "440",
						"400", "440",
						"470", "440",
						"470", "440",
						"470", "600",
						"720", "455",
						"720", "455"};
	DatasFishingQuestsCoordExact = {"270", "560",
						"430", "380", -- bree
						"450", "310", -- salle des rois
						"630", "380", -- salle du feu
						"450", "490",
						"850", "260",
						"540", "140", -- sury - kala
						"430", "300", -- galtrev
						"730", "500", -- neigebronne
						"730", "500", -- neigebronne
						"730", "500", -- neigebronne
						"730", "500", -- neigebronne
						"430", "430", -- edoras -- to be done
						"290", "590", -- quai edoras
						"645", "450", -- dol amroth
						"720", "455",
						"720", "455"};

----
